apiVersion: v1
kind: Secret
metadata:
  name: sal-secrets
  namespace: wksmgmt
type: Opaque
data:
  sal_admin_pass: {{ .Values.sal_admin_pass | b64enc | quote  }}
  sal_db_pass: {{ .Values.sal_db_pass | b64enc | quote }}
