apiVersion: v1
kind: Secret
metadata:
  name: munki-secrets
  namespace: wksmgmt
type: Opaque
data:
  munki-repo-sshfs-pass: "{{ .Values.munki_repo_sshfs_pass }}"
  munki-repo-sshfs-authorized-key: "{{ .Values.munki_repo_sshfs_authorized_key }}"

